name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  php73:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run lint
        run: composer lint
      - name: Run static analysis
        run: composer phpstan
      - name: Run tests
        run: composer test
